name: AWS ECS Deployment
on: [push]

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AwsAccessKeyId }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AwsSecretAccessKey }}
    steps:
    - uses: actions/checkout@v1
    - name: Terraform deploy
      timeout-minutes: 20
      if: startsWith(github.event.head_commit.message, 'DEPLOY')
      run: |
        ./scripts/terraform_backend.sh > backend.hcl
        terraform init -backend-config=backend.hcl -input=false
        terraform plan -input=false
        terraform apply -auto-approve -input=false
  terraform-destroy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AwsAccessKeyId }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AwsSecretAccessKey }}
    steps:
    - uses: actions/checkout@v1
    - name: Terraform destroy
      timeout-minutes: 20
      if: startsWith(github.event.head_commit.message, 'DESTROY')
      run: |
        ./scripts/terraform_backend.sh > backend.hcl
        terraform init -backend-config=backend.hcl -input=false
        terraform plan -input=false
        terraform destroy -auto-approve -input=false
